input_text:
  alive_dimmer_last_event_type:
    name: Alive Dimmer Last Event Type
    max: 60
    initial: ""
  big_deck_dimmer_last_event_type:
    name: Big Deck Dimmer Last Event Type
    max: 60
    initial: ""

input_number:
  alive_dimmer_last_event_ts:
    name: Alive Dimmer Last Event Timestamp
    min: 0
    max: 3000000000
    step: 0.001
    mode: box
  big_deck_dimmer_last_event_ts:
    name: Big Deck Dimmer Last Event Timestamp
    min: 0
    max: 3000000000
    step: 0.001
    mode: box

  alive_dimmer_alive_lights_target:
    name: Alive Lights Target Brightness
    min: 0
    max: 255
    step: 1
    mode: slider
  alive_dimmer_alive_lights_last_send_ts:
    name: Alive Lights Last Send Timestamp
    min: 0
    max: 3000000000
    step: 0.001
    mode: box
  alive_dimmer_alive_lights_last_event_ts:
    name: Alive Lights Last Event Timestamp
    min: 0
    max: 3000000000
    step: 0.001
    mode: box

  alive_dimmer_hammscape_target:
    name: Hammscape Target Brightness
    min: 0
    max: 255
    step: 1
    mode: slider
  alive_dimmer_hammscape_last_send_ts:
    name: Hammscape Last Send Timestamp
    min: 0
    max: 3000000000
    step: 0.001
    mode: box
  alive_dimmer_hammscape_last_event_ts:
    name: Hammscape Last Event Timestamp
    min: 0
    max: 3000000000
    step: 0.001
    mode: box

  big_deck_dimmer_asia_big_deck_target:
    name: Asia Big Deck Target Brightness
    min: 0
    max: 255
    step: 1
    mode: slider
  big_deck_dimmer_asia_big_deck_last_send_ts:
    name: Asia Big Deck Last Send Timestamp
    min: 0
    max: 3000000000
    step: 0.001
    mode: box
  big_deck_dimmer_asia_big_deck_last_event_ts:
    name: Asia Big Deck Last Event Timestamp
    min: 0
    max: 3000000000
    step: 0.001
    mode: box
