transition_late_weeknight_time:
  name: Late Transition Time (Weeknights)
  has_date: false
  has_time: true
  initial: '22:30:00'

transition_late_weekend_time:
  name: Late Transition Time (Weekends)
  has_date: false
  has_time: true
  initial: '00:00:00'
