id: shellies_announce
alias: Shellies Announce
triggers:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
actions:
  - service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce