id: '1742401610599'
alias: Alive dimmer (Alive lights)
description: ''
use_blueprint:
  path: dimmer_smooth_event.yaml
  input:
    event_entity: event.alive_dimmer
    target_light: light.alive_lights
    global_state_prefix: alive_dimmer
    target_state_prefix: alive_dimmer_alive_lights
    dim_state: rotate_left
    brighten_state: rotate_right
    toggle_state: press
    ignore_toggle_after_ms: 1000
    revolutions_full_range: 2
    steps_per_revolution: 24
    scale_factor: 1
    min_send_interval_ms: 150
    fade_ms: 300
    state_actions:
      - state: long_press
        action: button.press
        target:
          entity_id: button.google_pixel_8_google_pixel_8_play_sound