id: alive_dimmer_hammscape
alias: Alive dimmer (Hammscape)
description: ''
use_blueprint:
  path: dimmer_smooth_event.yaml
  input:
    event_entity: event.alive_dimmer
    target_light: light.hammscape
    global_state_prefix: alive_dimmer
    target_state_prefix: alive_dimmer_hammscape
    dim_state: rotate_left_pressed
    brighten_state: rotate_right_pressed
    toggle_state: ''
    ignore_toggle_after_ms: 1000
    revolutions_full_range: 2
    steps_per_revolution: 24
    scale_factor: 1
    min_send_interval_ms: 150
    fade_ms: 300
    state_actions: []
