id: '1742401610600'
alias: Asia's Dimmer
description: ''
use_blueprint:
  path: dimmer_smooth_event.yaml
  input:
    event_entity: event.big_deck_dimmer
    target_light: light.asia_big_deck
    global_state_prefix: big_deck_dimmer
    target_state_prefix: big_deck_dimmer_asia_big_deck
    dim_state: rotate_left
    brighten_state: rotate_right
    toggle_state: press
    ignore_toggle_after_ms: 1000
    revolutions_full_range: 2
    steps_per_revolution: 24
    scale_factor: 1
    min_send_interval_ms: 150
    fade_ms: 300
    state_actions: []