substitutions:
  name: demoled1
  description: "ESP8266 Demo LED 1"
  encryption_key: "D8TiTdcDzd24GHFpXZDtcP22663XXFQ5Vk4s/012w/s="
  ota_password: "570c9a1e6083dea98bf966899f11f2b7"
  num_leds: "60"
  pin: "D4"
  board: d1_mini
    
packages:
  common: !include rgb.led.template.yaml
