esphome:
  name: hammlights-3
  friendly_name: Hammlights 3

esp32:
  board: wemos_d1_mini32

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YfeB/oBrB/Hp65benxSZZxms+VCrJ3ff76+FJn2S9p0="

ota:
- platform: esphome
  password: "d1b5f2f9340ebe9f64d226948c40a461"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hammlights-3 Fallback Hotspot"
    password: "LYN0MRFPvNgM"

captive_portal:
    